PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `item` (`guid` text,`trim_id` text,`imdb_id` text,`tmdb_id` integer,`pinyin` text,`type` text,`lan` text,`title` text,`sort_title` text,`sort_num` integer DEFAULT 2147483647,`original_title` text,`overview` text,`adult` integer NOT NULL DEFAULT 0,`runtime` integer,`release_date` text,`parent_guid` text,`alternative_titles` text,`backdrops` text,`backdrop_height` integer DEFAULT 0,`backdrop_width` integer DEFAULT 0,`backdrop_height_width_try` integer DEFAULT 0,`logos` text,`posters` text,`poster_height` integer DEFAULT 0,`poster_width` integer DEFAULT 0,`poster_height_width_try` integer DEFAULT 0,`production_countries` text,`external_ids` text,`origin_country` text,`content_ratings` text,`first_air_date` text,`last_air_date` text,`air_date` text,`vote_average` real,`vote_count` integer,`number_of_seasons` integer,`number_of_episodes` integer,`status` text DEFAULT "1",`season_number` integer,`episode_number` integer,`still_path` text,`keywords` text,`path` text,`fetch_status` integer,`logic_type` integer DEFAULT 0,`dir` text,`filename` text,`episode_imdb_id` text,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
CREATE TABLE `item_ancestor` (`item_guid` text NOT NULL,`ancestor_guid` text NOT NULL,`create_time` integer,`update_time` integer);
CREATE TABLE `item_media` (`guid` text,`item_guid` text NOT NULL,`dir` text DEFAULT "",`path` text NOT NULL,`size` integer,`can_play` integer DEFAULT 1,`type` integer NOT NULL,`mod_time` integer,`file_hash` text,`create_time` integer,`update_time` integer,`file_birth_time` integer,`recognition_status` integer DEFAULT 1,`progress_thumb_hash_dir` text,`progress_thumb_errno` integer,`cloud_storage_type` integer,`mount_path` text,`fid` text,`pick_code` text,`content_hash` text,PRIMARY KEY (`guid`));
CREATE TABLE `item_person` (`item_guid` text NOT NULL,`person_guid` text NOT NULL,`role` text,`job` text,`order` integer,`department` text);
CREATE TABLE `item_tag` (`item_guid` text NOT NULL,`tag` text NOT NULL,`type` text);
CREATE TABLE `item_user` (`user_guid` text NOT NULL,`item_guid` text NOT NULL,`is_admin` integer NOT NULL,`create_time` integer,`update_time` integer);
CREATE TABLE `item_user_favorite` (`user_guid` text NOT NULL,`item_guid` text NOT NULL,`item_type` text,`create_time` integer,`update_time` integer);
CREATE TABLE `item_user_play` (`item_guid` text NOT NULL,`user_guid` text NOT NULL,`ts` integer DEFAULT 0,`watched` integer DEFAULT 0,`media_guid` text,`video_guid` text,`audio_guid` text,`subtitle_guid` text,`direct_link_audio_index` integer DEFAULT -1,`resolution` text,`bitrate` integer,`type` text,`visible` integer DEFAULT 1,`create_time` integer,`update_time` integer);
CREATE TABLE `media_delete` (`ancestor_guid` text NOT NULL,`media_path` text NOT NULL,`dir` text DEFAULT "",`is_dir` numeric DEFAULT false,`create_time` integer,`update_time` integer);
CREATE TABLE `media_property` (`media_guid` text NOT NULL,`category` text,`content` text,`update_time` integer,`create_time` integer);
CREATE TABLE `media_server` (`guid` text NOT NULL,`name` text,`lan` text,`meta_dir` text,`file_monitor` integer,`region` text,`direct_link_enable` integer DEFAULT 1,`direct_link_allowed_level` integer DEFAULT 0,`direct_link_allowed_drives` text,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
INSERT INTO media_server VALUES('24acb7d71a05482e8f4b6b4097d39373','MediaHub','zh-CN','/vol1/@appmeta/trim.media',1,'CN',1,0,'',1764039737866,1764039737866);
CREATE TABLE `media_stream` (`guid` text NOT NULL,`title` text,`media_guid` text NOT NULL,`codec_name` text,`codec_type` text,`color_range` text,`profile` text,`index` integer,`width` integer,`height` integer,`coded_width` integer,`coded_height` integer,`display_aspect_ratio` text,`pix_fmt` text,`level` text,`color_space` text,`color_transfer` text,`color_primaries` text,`dv_profile` integer NOT NULL DEFAULT 0,`refs` integer,`rotation` real,`r_frame_rate` text,`avg_frame_rate` text,`time_base` text,`start_pts` integer,`start_time` text,`duration_pts` integer,`duration` integer,`is_default` integer,`forced` integer,`bps` integer,`language` text,`channels` integer,`sample_rate` text,`bits_per_raw_sample` text,`is_external` integer,`channel_layout` text,`create_time` integer,`update_time` integer,`resolution_type` text,`audio_type` text,`color_range_type` text,`bit_depth` integer,`progressive` integer,`origin_filename` text,`filepath` text,`source_id` text,`source` text,`trim_id` text,`release` text,`uploader` text,`status` integer NOT NULL DEFAULT 1,`ext1` integer DEFAULT 0,`container_format` text,`is_bluray` numeric DEFAULT false,`key_frame_interval` integer,PRIMARY KEY (`guid`));
CREATE TABLE `mediadb_config` (`item_guid` text NOT NULL,`subtitle_lan` text,`auto_scrap_subtitle` integer,`category` text,`create_time` integer,`update_time` integer,`include_adult` numeric DEFAULT false,`view_type` integer DEFAULT 0,`auto_progress_thumb` integer DEFAULT 0,`skip_filesize` integer DEFAULT 0);
CREATE TABLE `permission` (`permission` text NOT NULL,`create_time` integer,`update_time` integer);
INSERT INTO permission VALUES('mdb_manager',1764039562954,1764039562954);
INSERT INTO permission VALUES('user_manager',1764039562954,1764039562954);
INSERT INTO permission VALUES('metadata_manager',1764039562954,1764039562954);
INSERT INTO permission VALUES('server_manager',1764039562954,1764039562954);
INSERT INTO permission VALUES('task_manager',1764039562954,1764039562954);
CREATE TABLE `person` (`guid` text NOT NULL,`trim_id` text,`imdb_id` text,`tmdb_id` integer,`lan` text NOT NULL,`pinyin` text,`name` text,`original_name` text,`also_know_as` text,`biography` text,`know_for_department` text,`images` text,`profile_path` text,`gender` integer,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
CREATE TABLE `schedule` (`guid` text NOT NULL,`name` text,`type` text,`interval` integer,`status` integer NOT NULL DEFAULT 1,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
INSERT INTO schedule VALUES('schedule-item-scrap','scrap-item','TaskItemScrap',86400,1,1764039562954,1764039562954);
INSERT INTO schedule VALUES('schedule-subtitle-extra','extra-subtitle','TaskSubtitleExtra',86400,1,1764039562954,1764039562954);
CREATE TABLE `sys_metadata` (`key` text NOT NULL,`value` text,`private` integer,`create_time` integer,`update_time` integer,PRIMARY KEY (`key`));
INSERT INTO sys_metadata VALUES('db_version','9',0,1764039563,1764039563);
INSERT INTO sys_metadata VALUES('global_task_switch','1',0,1764039563,1764039563);
INSERT INTO sys_metadata VALUES('defaultmetadir','/vol1/@appmeta/trim.media',0,1764039564,1764039564);
INSERT INTO sys_metadata VALUES('sys_secret','568ba6e4e64f38ed08e249538849dea95b7d542c36361eba05bacc1ce696f632c',1,1764039737,1764039737);
INSERT INTO sys_metadata VALUES('mediasrv_cache_dir','/vol1',0,1764039737,1764039737);
CREATE TABLE `tag` (`guid` text NOT NULL,`tag` text NOT NULL,`type` text,`trim_id` text,PRIMARY KEY (`guid`));
CREATE TABLE `user` (`guid` text,`username` text,`passwd` text,`lan` text,`last_login_time` integer,`is_admin` integer,`media_permission` integer,`status` integer,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
INSERT INTO user VALUES('default-user-template','user-template',NULL,NULL,NULL,0,1,0,1764039562954,1764039562954);
INSERT INTO user VALUES('62ea6f528af04dd3977bd364c4148c01','admin','dJp5/s0mfAaCA1d1p3YTxQBVDJJmQzJb3K/dNghHRLM=','zh-CN',1764039737,1,2,1,1764039737913,1764039737913);
CREATE TABLE `user_permission` (`user_guid` text NOT NULL,`permission` text NOT NULL,`status` integer NOT NULL DEFAULT 1,`create_time` integer,`update_time` integer);
CREATE TABLE `user_source` (`user_guid` text NOT NULL,`source_id` text NOT NULL,`source` text NOT NULL,`source_name` text,`create_time` integer,`update_time` integer);
INSERT INTO user_source VALUES('62ea6f528af04dd3977bd364c4148c01','1000','Trim-NAS','admin',1764039637294,1764039637294);
CREATE TABLE `download_task` (`guid` text NOT NULL,`media_guid` text NOT NULL,`user_guid` text NOT NULL,`resolution` text NOT NULL,`media_file` text NOT NULL,`output_file` text NOT NULL,`status` integer NOT NULL DEFAULT 0,`direct_download` integer NOT NULL DEFAULT 0,`create_time` integer,`update_time` integer,PRIMARY KEY (`guid`));
CREATE TABLE `item_play_config` (`item_guid` text,`user_guid` text,`skip_opening` integer,`skip_ending` integer,PRIMARY KEY (`item_guid`,`user_guid`));
CREATE INDEX `idx_dir` ON `item`(`dir`);
CREATE INDEX `idx_path` ON `item`(`path`);
CREATE INDEX `idx_parent_guid` ON `item`(`parent_guid`);
CREATE INDEX `idx_tmdb_id` ON `item`(`tmdb_id`);
CREATE INDEX `idx_imdb_id` ON `item`(`imdb_id`);
CREATE INDEX `idx_trim_id` ON `item`(`trim_id`);
CREATE INDEX `idx_ancestor_guid` ON `item_ancestor`(`ancestor_guid`);
CREATE INDEX `idx_itemancestor_item_guid` ON `item_ancestor`(`item_guid`);
CREATE INDEX `idx_file_hash` ON `item_media`(`file_hash`);
CREATE INDEX `idx_itemmedia_path` ON `item_media`(`path`);
CREATE INDEX `idx_itemmedia_dir` ON `item_media`(`dir`);
CREATE INDEX `idx_itemmedia_item_guid` ON `item_media`(`item_guid`);
CREATE INDEX `idx_person_guid` ON `item_person`(`person_guid`);
CREATE INDEX `idx_itemperson_item_guid` ON `item_person`(`item_guid`);
CREATE INDEX `idx_itemtag_tag` ON `item_tag`(`tag`);
CREATE INDEX `idx_item_tag_guid` ON `item_tag`(`item_guid`);
CREATE UNIQUE INDEX `uk_user_item` ON `item_user`(`user_guid`,`item_guid`);
CREATE INDEX `idx_itemuserfavorite_item_guid` ON `item_user_favorite`(`item_guid`);
CREATE INDEX `idx_itemuserfavorite_user_guid` ON `item_user_favorite`(`user_guid`);
CREATE INDEX `idx_itemuserplay_user_guid` ON `item_user_play`(`user_guid`);
CREATE UNIQUE INDEX `uk_item_user` ON `item_user_play`(`item_guid`,`user_guid`);
CREATE INDEX `idx_itemuserplay_item_guid` ON `item_user_play`(`item_guid`);
CREATE INDEX `idx_mediadelete_dir` ON `media_delete`(`dir`);
CREATE UNIQUE INDEX `uk_ancestor_path` ON `media_delete`(`ancestor_guid`,`media_path`);
CREATE INDEX `idx_mediaproperty_media_guid` ON `media_property`(`media_guid`);
CREATE INDEX `idx_filepath` ON `media_stream`(`filepath`);
CREATE INDEX `idx_mediastream_media_guid` ON `media_stream`(`media_guid`);
CREATE INDEX `idx_mediadbconfig_item_guid` ON `mediadb_config`(`item_guid`);
CREATE INDEX `idx_permission` ON `permission`(`permission`);
CREATE INDEX `idx_person_tmdb_id` ON `person`(`tmdb_id`);
CREATE INDEX `idx_person_imdb_id` ON `person`(`imdb_id`);
CREATE INDEX `idx_person_trim_id` ON `person`(`trim_id`);
CREATE INDEX `idx_tag_tag` ON `tag`(`tag`);
CREATE UNIQUE INDEX `uk_username` ON `user`(`username`);
CREATE UNIQUE INDEX `uk_user_guid_permission` ON `user_permission`(`user_guid`,`permission`);
CREATE UNIQUE INDEX `uk_user_guid_source` ON `user_source`(`user_guid`,`source_id`,`source`);
CREATE INDEX `idx_user_guid` ON `download_task`(`user_guid`);
CREATE INDEX `idx_task_guid` ON `download_task`(`media_guid`);
CREATE UNIQUE INDEX idx_item_guid_path ON item_media(item_guid, path);
COMMIT;